### ISSUE TITLE
Crash of Reaper When Editing sfz-File

### ISSUE THREAD

**Issue by koalastudio72** [sfztools/sfizz-ui#2] opened 2023-04-16 13:30 UTC
Hi,
regarding the latest versions of sfizz (incl. 1.2.1), it works really very well in Reaper with one exception:
1) I open a sfz-file in sfizz for editing (for example a little tweaking of opcode values)
2) I save the file -> then Reaper completely crashes.

This happens every time without exception.

I use Reaper 6.78  and sfizz 1.2.1 on a Windows 10 machine.

Any idea ?

Thanks in advance
Daniel

**Comment by redtide** [comment] 2023-04-16 13:36
Hello,
the only thing that comes to mind is the file reloading, I'll take a look.
Thank you for the report!

**Comment by SirGawain99** [comment] 2023-05-15 17:05
I can confirm that I've experienced the same issue in Reaper on Linux Mint since 19.3 (now 21.1) when editing a sfz files in gedit while it's loaded in the Sfizz vst3.

For me, it doesn't crash every time, but I haven't identified the sequence of events that causes it. When busy on a large or critical project, I find it safer to temporarily load an alternative sfz while editing the one I need. Not ideal, but I thought this was peculiar to my system.

**Comment by koalastudio72** [comment] 2023-05-17 14:37
Hi SirGawain99,
thanks for your comment.
Strange to say that during the time I wrote my first comment, the crashes occured really every time I tried to edit a sfz-file.
I still use the same version of Reaper, sfizz and the same computer, but the crashes decreased. Now, most of the time I can edit without crashes.
Perhaps something to do with the size of the file. But I didn't do enough tests until now to prove this assumption.
Your workaround is a good alternative to use sfizz productive.

**Comment by redtide** [comment] 2023-05-17 15:26
Currently my Windows setup needs some work but I tried with my main Linux system with the current develop branch version, Church Steinway piano and Kitchen-X instruments. No problem with the piano but with Kitchen X didn't take long to face the problem and I'm afraid it will take a while to be solved due the lack of time (and people) to work on sfizz at this time.
For now I can only create a [milestone](https://github.com/sfztools/sfizz-ui/milestone/1) and give this some priority.

**Comment by koalastudio72** [comment] 2023-05-17 17:19
Hi redtide,
thanks for giving priority.
At the moment this is only a little problem for me, because I don't edit sfz-files every day. Would be great to see solved in an updated version.
Nevertheless thanks so much for your great work til now. I use sfizz in many of my live projects and it works very solid in play mode.

**Comment by redtide** [comment] 2023-05-17 17:28
thank you but the main work is made by paulfd and jpcima, I'm helping with some tasks

**Comment by SirGawain99** [comment] 2023-05-24 14:55
I hope the devs know how much we appreciate their efforts to perfect this awesome product. Editing SFZ's on the fly is probably not the task of choice for most productive muzo's, so I doubt this problem represents a high-priority issue. It's just good to reassure fellow instrument editors that they're not alone with the odd quirk.

**Comment by redtide** [comment] 2023-05-24 15:27
Thank you!
It's not about priority but lack of manpower. This issue is on top of the list of the 1.3.0 milestone, I wonder if related in some way with #16, though LV2 has different code base.
I think it's not about file editing issue because it doesn't affect the workflow until you save it, then it's about reloading and if the application permits to do so during runtime, a crash is not something acceptable.

**Comment by essej** [comment] 2023-05-27 21:54
This PR should fix it: https://github.com/sfztools/sfizz/pull/1170

**Comment by paulfd** [comment] 2024-01-01 22:22
Is this fixed in the end?

**Comment by koalastudio72** [comment] 2024-01-01 23:02
> Is this fixed in the end?

Hi,
since the release of 1.2.2 all works perfect for me in Reaper. Seems to be fixed !
Thanks a lot to the devs.

**Closed as completed** 2024-01-02 00:48 UTC
